{
 "title": "Seeonline-service(service)",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Основные", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Методы - график",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "django_http_requests_total_by_method_total{method=\"GET\"}",
     "legendFormat": "GET"
    },
    {
     "expr": "django_http_requests_total_by_method_total{method=\"POST\"}",
     "legendFormat": "POST"
    },
    {
     "expr": "django_http_requests_total_by_method_total{method=\"PATCH\"}",
     "legendFormat": "PATCH"
    },
    {
     "expr": "django_http_requests_total_by_method_total{method=\"DELETE\"}",
     "legendFormat": "DELETE"
    }
   ]
  },
  {
   "title": "Методы - счетчик",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "django_http_requests_total_by_method_total{method=\"GET\"}",
     "legendFormat": "GET"
    },
    {
     "expr": "django_http_requests_total_by_method_total{method=\"POST\"}",
     "legendFormat": "POST"
    },
    {
     "expr": "django_http_requests_total_by_method_total{method=\"PATCH\"}",
     "legendFormat": "PATCH"
    },
    {
     "expr": "django_http_requests_total_by_method_total{method=\"DELETE\"}",
     "legendFormat": "DELETE"
    }
   ]
  },
  {
   "title": "Запросы(до middleware)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "django_http_requests_before_middlewares_total",
     "legendFormat": "Запросы"
    }
   ]
  },
  {
   "title": "Статус коды ответов",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "django_http_responses_total_by_status_total{status=\"100\"}",
     "legendFormat": "100"
    },
    {
     "expr": "django_http_responses_total_by_status_total{status=\"101\"}",
     "legendFormat": "101"
    },
    {
     "expr": "django_http_responses_total_by_status_total{status=\"102\"}",
     "legendFormat": "102"
    },
    {
     "expr": "django_http_responses_total_by_status_total{status=\"103\"}",
     "legendFormat": "103"
    },
    {
     "expr": "django_http_responses_total_by_status_total{status=\"200\"}",
     "legendFormat": "200"
    },
    {
     "expr": "django_http_responses_total_by_status_total{status=\"201\"}",
     "legendFormat": "201"
    },
    {
     "expr": "django_http_responses_total_by_status_total{status=\"202\"}",
     "legendFormat": "202"
    },
    {
     "expr": "django_http_responses_total_by_status_total{status=\"204\"}",
     "legendFormat": "204"
    },
    {
     "expr": "django_http_responses_total_by_status_total{status=\"301\"}",
     "legendFormat": "301"
    },
    {
     "expr": "django_http_responses_total_by_status_total{status=\"302\"}",
     "legendFormat": "302"
    },
    {
     "expr": "django_http_responses_total_by_status_total{status=\"303\"}",
     "legendFormat": "303"
    },
    {
     "expr": "django_http_responses_total_by_status_total{status=\"304\"}",
     "legendFormat": "304"
    },
    {
     "expr": "django_http_responses_total_by_status_total{status=\"307\"}",
     "legendFormat": "307"
    },
    {
     "expr": "django_http_responses_total_by_status_total{status=\"308\"}",
     "legendFormat": "308"
    },
    {
     "expr": "django_http_responses_total_by_status_total{status=\"400\"}",
     "legendFormat": "400"
    },
    {
     "expr": "django_http_responses_total_by_status_total{status=\"401\"}",
     "legendFormat": "401"
    },
    {
     "expr": "django_http_responses_total_by_status_total{status=\"404\"}",
     "legendFormat": "404"
    },
    {
     "expr": "django_http_responses_total_by_status_total{status=\"405\"}",
     "legendFormat": "405"
    },
    {
     "expr": "django_http_responses_total_by_status_total{status=\"406\"}",
     "legendFormat": "406"
    },
    {
     "expr": "django_http_responses_total_by_status_total{status=\"408\"}",
     "legendFormat": "408"
    },
    {
     "expr": "django_http_responses_total_by_status_total{status=\"409\"}",
     "legendFormat": "409"
    },
    {
     "expr": "django_http_responses_total_by_status_total{status=\"410\"}",
     "legendFormat": "410"
    },
    {
     "expr": "django_http_responses_total_by_status_total{status=\"413\"}",
     "legendFormat": "413"
    },
    {
     "expr": "django_http_responses_total_by_status_total{status=\"415\"}",
     "legendFormat": "415"
    },
    {
     "expr": "django_http_responses_total_by_status_total{status=\"429\"}",
     "legendFormat": "429"
    },
    {
     "expr": "django_http_responses_total_by_status_total{status=\"500\"}",
     "legendFormat": "500"
    },
    {
     "expr": "django_http_responses_total_by_status_total{status=\"501\"}",
     "legendFormat": "501"
    },
    {
     "expr": "django_http_responses_total_by_status_total{status=\"502\"}",
     "legendFormat": "502"
    },
    {
     "expr": "django_http_responses_total_by_status_total{status=\"504\"}",
     "legendFormat": "504"
    },
    {
     "expr": "django_http_responses_total_by_status_total{status=\"507\"}",
     "legendFormat": "507"
    }
   ]
  },
  { "title": "Запросы к эндпоинтам", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "OnlineStatus",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "django_http_requests_latency_seconds_by_view_method_count{view=\"onlinestatus-by-tracked-user-id\"}",
     "legendFormat": "by-tracked-user-id"
    },
    {
     "expr": "django_http_requests_latency_seconds_by_view_method_count{view=\"onlinestatus-by-tracked-username\"}",
     "legendFormat": "by-tracked-username"
    },
    {
     "expr": "django_http_requests_latency_seconds_by_view_method_count{view=\"onlinestatus-detail\"}",
     "legendFormat": "detail"
    },
    {
     "expr": "django_http_requests_latency_seconds_by_view_method_count{view=\"onlinestatus-list\"}",
     "legendFormat": "list"
    }
   ]
  },
  {
   "title": "OnlineStatus-list",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "django_http_requests_latency_seconds_by_view_method_count{view=\"onlinestatus-list\", method=\"GET\"}",
     "legendFormat": "GET"
    },
    {
     "expr": "django_http_requests_latency_seconds_by_view_method_count{view=\"onlinestatus-list\", method=\"POST\"}",
     "legendFormat": "POST"
    }
   ]
  },
  {
   "title": "OnlineStatus-detail",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "django_http_requests_latency_seconds_by_view_method_count{view=\"onlinestatus-detail\", method=\"GET\"}",
     "legendFormat": "GET"
    },
    {
     "expr": "django_http_requests_latency_seconds_by_view_method_count{view=\"onlinestatus-detail\", method=\"PATCH\"}",
     "legendFormat": "PATCH"
    },
    {
     "expr": "django_http_requests_latency_seconds_by_view_method_count{view=\"onlinestatus-detail\", method=\"DELETE\"}",
     "legendFormat": "DELETE"
    }
   ]
  },
  {
   "title": "TelegramUser (суммарный график)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "django_http_requests_latency_seconds_by_view_method_count{view=\"telegramuser-list\"}",
     "legendFormat": "telegramuser-list"
    },
    {
     "expr": "django_http_requests_latency_seconds_by_view_method_count{view=\"telegramuser-detail\"}",
     "legendFormat": "telegramuser-detail"
    },
    {
     "expr": "django_http_requests_latency_seconds_by_view_method_count{view=\"telegramuser-by-telegram-id\"}",
     "legendFormat": "by-telegram-id"
    },
    {
     "expr": "django_http_requests_latency_seconds_by_view_method_count{view=\"telegramuser-by-role\"}",
     "legendFormat": "by-role"
    }
   ]
  },
  {
   "title": "OnlineStatus-by-tracked-user-id",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "django_http_requests_latency_seconds_by_view_method_count{view=\"onlinestatus-by-tracked-user-id\", method=\"DELETE\"}",
     "legendFormat": "DELETE"
    }
   ]
  },
  {
   "title": "OnlineStatus-by-tracked-username",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "targets": [
    {
     "expr": "django_http_requests_latency_seconds_by_view_method_count{view=\"onlinestatus-by-tracked-username\", method=\"DELETE\"}",
     "legendFormat": "DELETE"
    }
   ]
  },
  { "title": "TrackerAccount", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "TrackerAccount (суммарный график)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 60 },
   "targets": [
    {
     "expr": "django_http_requests_latency_seconds_by_view_method_count{view=\"trackeraccount-list\"}",
     "legendFormat": "trackeraccount-list"
    },
    {
     "expr": "django_http_requests_latency_seconds_by_view_method_count{view=\"trackeraccount-detail\"}",
     "legendFormat": "trackeraccount-detail"
    },
    {
     "expr": "django_http_requests_latency_seconds_by_view_method_count{view=\"trackeraccount-by-telegram-id\"}",
     "legendFormat": "by-telegram-id"
    }
   ]
  },
  {
   "title": "TrackerAccount-list",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
   "targets": [
    {
     "expr": "django_http_requests_latency_seconds_by_view_method_count{view=\"trackeraccount-list\", method=\"GET\"}",
     "legendFormat": "GET"
    },
    {
     "expr": "django_http_requests_latency_seconds_by_view_method_count{view=\"trackeraccount-list\", method=\"POST\"}",
     "legendFormat": "POST"
    }
   ]
  },
  {
   "title": "TrackerAccount-detail",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
   "targets": [
    {
     "expr": "django_http_requests_latency_seconds_by_view_method_count{view=\"trackeraccount-detail\", method=\"GET\"}",
     "legendFormat": "GET"
    },
    {
     "expr": "django_http_requests_latency_seconds_by_view_method_count{view=\"trackeraccount-detail\", method=\"PATCH\"}",
     "legendFormat": "PATCH"
    },
    {
     "expr": "django_http_requests_latency_seconds_by_view_method_count{view=\"trackeraccount-detail\", method=\"DELETE\"}",
     "legendFormat": "DELETE"
    }
   ]
  },
  {
   "title": "TrackerAccount-by-telegram-id",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 77 },
   "targets": [
    {
     "expr": "django_http_requests_latency_seconds_by_view_method_count{view=\"trackeraccount-by-telegram-id\", method=\"PATCH\"}",
     "legendFormat": "PATCH"
    },
    {
     "expr": "django_http_requests_latency_seconds_by_view_method_count{view=\"trackeraccount-by-telegram-id\", method=\"DELETE\"}",
     "legendFormat": "DELETE"
    }
   ]
  },
  { "title": "TrackerSetting", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 } },
  {
   "title": "TrackerSetting (суммарно)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 86 },
   "targets": [
    {
     "expr": "django_http_requests_latency_seconds_by_view_method_count{view=\"trackersetting-list\"}",
     "legendFormat": "trackersetting-list"
    },
    {
     "expr": "django_http_requests_latency_seconds_by_view_method_count{view=\"trackersetting-detail\"}",
     "legendFormat": "trackersetting-detail"
    },
    {
     "expr": "django_http_requests_latency_seconds_by_view_method_count{view=\"trackersetting-by-phone-number\"}",
     "legendFormat": "by-phone-number"
    },
    {
     "expr": "django_http_requests_latency_seconds_by_view_method_count{view=\"trackersetting-by-tracker-telegram-id\"}",
     "legendFormat": "by-tracker-telegram-id"
    }
   ]
  },
  {
   "title": "TrackerSetting-list",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 95 },
   "targets": [
    {
     "expr": "django_http_requests_latency_seconds_by_view_method_count{view=\"trackersetting-list\", method=\"GET\"}",
     "legendFormat": "GET"
    },
    {
     "expr": "django_http_requests_latency_seconds_by_view_method_count{view=\"trackersetting-list\", method=\"POST\"}",
     "legendFormat": "POST"
    }
   ]
  },
  {
   "title": "TrackerSetting-detail",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 95 },
   "targets": [
    {
     "expr": "django_http_requests_latency_seconds_by_view_method_count{view=\"trackersetting-detail\", method=\"GET\"}",
     "legendFormat": "GET"
    },
    {
     "expr": "django_http_requests_latency_seconds_by_view_method_count{view=\"trackersetting-detail\", method=\"PATCH\"}",
     "legendFormat": "PATCH"
    },
    {
     "expr": "django_http_requests_latency_seconds_by_view_method_count{view=\"trackersetting-detail\", method=\"DELETE\"}",
     "legendFormat": "DELETE"
    }
   ]
  },
  {
   "title": "TrackerSetting-by-phone-number",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 103 },
   "targets": [
    {
     "expr": "django_http_requests_latency_seconds_by_view_method_count{view=\"trackersetting-by-phone-number\", method=\"PATCH\"}",
     "legendFormat": "PATCH"
    },
    {
     "expr": "django_http_requests_latency_seconds_by_view_method_count{view=\"trackersetting-by-phone-number\", method=\"DELETE\"}",
     "legendFormat": "DELETE"
    }
   ]
  },
  {
   "title": "TrackerSetting-by-tracker-telegram-id",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 103 },
   "targets": [
    {
     "expr": "django_http_requests_latency_seconds_by_view_method_count{view=\"trackersetting-by-tracker-telegram-id\", method=\"PATCH\"}",
     "legendFormat": "PATCH"
    },
    {
     "expr": "django_http_requests_latency_seconds_by_view_method_count{view=\"trackersetting-by-tracker-telegram-id\", method=\"DELETE\"}",
     "legendFormat": "DELETE"
    }
   ]
  },
  { "title": "TelegramUser", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 111 } },
  {
   "title": "TelegramUser-list",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 112 },
   "targets": [
    {
     "expr": "django_http_requests_latency_seconds_by_view_method_count{view=\"telegramuser-list\", method=\"GET\"}",
     "legendFormat": "GET"
    },
    {
     "expr": "django_http_requests_latency_seconds_by_view_method_count{view=\"telegramuser-list\", method=\"POST\"}",
     "legendFormat": "POST"
    }
   ]
  },
  {
   "title": "TelegramUser-detail",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 112 },
   "targets": [
    {
     "expr": "django_http_requests_latency_seconds_by_view_method_count{view=\"telegramuser-detail\", method=\"GET\"}",
     "legendFormat": "GET"
    },
    {
     "expr": "django_http_requests_latency_seconds_by_view_method_count{view=\"telegramuser-detail\", method=\"PATCH\"}",
     "legendFormat": "PATCH"
    },
    {
     "expr": "django_http_requests_latency_seconds_by_view_method_count{view=\"telegramuser-detail\", method=\"DELETE\"}",
     "legendFormat": "DELETE"
    }
   ]
  },
  {
   "title": "TelegramUser-by-telegram-id",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 120 },
   "targets": [
    {
     "expr": "django_http_requests_latency_seconds_by_view_method_count{view=\"telegramuser-by-telegram-id\", method=\"PATCH\"}",
     "legendFormat": "PATCH"
    },
    {
     "expr": "django_http_requests_latency_seconds_by_view_method_count{view=\"telegramuser-by-telegram-id\", method=\"DELETE\"}",
     "legendFormat": "DELETE"
    }
   ]
  },
  {
   "title": "TelegramUser-by-role",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 120 },
   "targets": [
    {
     "expr": "django_http_requests_latency_seconds_by_view_method_count{view=\"telegramuser-by-role\", method=\"PATCH\"}",
     "legendFormat": "PATCH"
    },
    {
     "expr": "django_http_requests_latency_seconds_by_view_method_count{view=\"telegramuser-by-role\", method=\"DELETE\"}",
     "legendFormat": "DELETE"
    }
   ]
  },
  { "title": "TrackedUser", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 128 } },
  {
   "title": "TrackedUser (суммарно)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 129 },
   "targets": [
    {
     "expr": "django_http_requests_latency_seconds_by_view_method_count{view=\"trackeduser-list\"}",
     "legendFormat": "trackeduser-list"
    },
    {
     "expr": "django_http_requests_latency_seconds_by_view_method_count{view=\"trackeduser-detail\"}",
     "legendFormat": "trackeduser-detail"
    },
    {
     "expr": "django_http_requests_latency_seconds_by_view_method_count{view=\"trackeduser-by-username\"}",
     "legendFormat": "by-username"
    }
   ]
  },
  {
   "title": "TrackedUser-list",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 138 },
   "targets": [
    {
     "expr": "django_http_requests_latency_seconds_by_view_method_count{view=\"trackeduser-list\", method=\"GET\"}",
     "legendFormat": "GET"
    },
    {
     "expr": "django_http_requests_latency_seconds_by_view_method_count{view=\"trackeduser-list\", method=\"POST\"}",
     "legendFormat": "POST"
    }
   ]
  },
  {
   "title": "TrackedUser-detail",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 138 },
   "targets": [
    {
     "expr": "django_http_requests_latency_seconds_by_view_method_count{view=\"trackeduser-detail\", method=\"GET\"}",
     "legendFormat": "GET"
    },
    {
     "expr": "django_http_requests_latency_seconds_by_view_method_count{view=\"trackeduser-detail\", method=\"PATCH\"}",
     "legendFormat": "PATCH"
    },
    {
     "expr": "django_http_requests_latency_seconds_by_view_method_count{view=\"trackeduser-detail\", method=\"DELETE\"}",
     "legendFormat": "DELETE"
    }
   ]
  },
  {
   "title": "TrackedUser-by-username",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 146 },
   "targets": [
    {
     "expr": "django_http_requests_latency_seconds_by_view_method_count{view=\"trackeduser-by-username\", method=\"PATCH\"}",
     "legendFormat": "PATCH"
    },
    {
     "expr": "django_http_requests_latency_seconds_by_view_method_count{view=\"trackeduser-by-username\", method=\"DELETE\"}",
     "legendFormat": "DELETE"
    }
   ]
  },
  { "title": "Дополнительные метрики", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 154 } },
  {
   "title": "Requests/s по эндпоинтам и методам",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 155 },
   "targets": [
    {
     "expr": "rate(django_http_requests_total_by_view_transport_method_total[1m])",
     "legendFormat": "{{view}} ({{method}}) req/s"
    }
   ]
  },
  {
   "title": "Requests/s по методам (суммарно)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 169 },
   "targets": [
    {
     "expr": "sum by (method) (rate(django_http_requests_total_by_method_total[1m]))",
     "legendFormat": "{{method}} req/s"
    }
   ]
  }
 ]
}