{
 "title": "Seeonline-service(python)",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Количество сборок GC",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "python_gc_collections_total{generation=\"0\"}",
     "legendFormat": "Поколение - 0"
    },
    {
     "expr": "python_gc_collections_total{generation=\"1\"}",
     "legendFormat": "Поколение - 1"
    },
    {
     "expr": "python_gc_collections_total{generation=\"2\"}",
     "legendFormat": "Поколение - 2"
    }
   ]
  },
  {
   "title": "Объекты не собранные GC",
   "type": "timeseries",
   "description": "Обекты которые Garbage Collector не смог собрать",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "python_gc_objects_uncollectable_total{generation=\"0\"}",
     "legendFormat": "Поколение - 0"
    },
    {
     "expr": "python_gc_objects_uncollectable_total{generation=\"1\"}",
     "legendFormat": "Поколение - 1"
    },
    {
     "expr": "python_gc_objects_uncollectable_total{generation=\"2\"}",
     "legendFormat": "Поколение - 2"
    }
   ]
  },
  {
   "title": "Общее потребление памяти (MB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "process_resident_memory_bytes / 1024 / 1024",
     "legendFormat": "Резидентная память (MB)"
    },
    {
     "expr": "process_virtual_memory_bytes / 1024 / 1024",
     "legendFormat": "Виртуальная память (MB)"
    }
   ]
  },
  {
   "title": "Нагрузка CPU (rate)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[1m])",
     "legendFormat": "rate CPU (сек/сек)"
    }
   ]
  }
 ]
}