# Generated by Django 5.1.6 on 2025-02-27 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_user_id', models.IntegerField(unique=True)),
                ('role', models.CharField(choices=[('banned', 'Banned'), ('user', 'User'), ('vip', 'VIP'), ('admin', 'Administrator')], default='user', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Telegram-пользователь',
                'verbose_name_plural': 'Telegram-пользователи',
            },
        ),
        migrations.CreateModel(
            name='TrackerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_user_id', models.IntegerField(unique=True)),
                ('api_id', models.PositiveIntegerField(unique=True)),
                ('api_hash', models.CharField(max_length=32, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_auth', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Трекер аккаунт',
                'verbose_name_plural': 'Трекер аккаунты',
            },
        ),
        migrations.CreateModel(
            name='TrackedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('visible_online', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('telegram_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracked_users', to='tracker.telegramuser')),
                ('tracker_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracked_users', to='tracker.trackeraccount')),
            ],
            options={
                'verbose_name': 'Отслеживаемый пользователь',
                'verbose_name_plural': 'Отслеживаемые пользователи',
            },
        ),
        migrations.CreateModel(
            name='OnlineStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_online', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tracked_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='online_statuses', to='tracker.trackeduser')),
            ],
            options={
                'verbose_name': 'Статус онлайн',
                'verbose_name_plural': 'Статусы онлайн',
            },
        ),
        migrations.CreateModel(
            name='TrackerSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('session_string', models.TextField(max_length=512, unique=True)),
                ('max_users', models.PositiveSmallIntegerField(default=0)),
                ('current_users', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tracker_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='setting', to='tracker.trackeraccount')),
            ],
            options={
                'verbose_name': 'Настройки трекера',
                'verbose_name_plural': 'Настройки трекера',
            },
        ),
    ]
