# Generated by Django 5.1.6 on 2025-02-27 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='telegram_user_id',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='trackeraccount',
            name='telegram_user_id',
            field=models.BigIntegerField(unique=True),
        ),
    ]
