# Generated by Django 5.1.6 on 2025-02-27 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_telegramuser_telegram_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackersetting',
            name='session_string',
            field=models.TextField(default=None, max_length=512, unique=True),
        ),
    ]
