# Generated by Django 5.1.6 on 2025-02-28 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_remove_onlinestatus_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='current_users',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='max_users',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
