# Generated by Django 5.1.6 on 2025-02-28 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_telegramuser_current_users_telegramuser_max_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telegramuser',
            old_name='telegram_user_id',
            new_name='telegram_id',
        ),
    ]
