# Generated by Django 5.1.6 on 2025-02-28 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_rename_telegram_user_id_telegramuser_telegram_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trackeraccount',
            old_name='telegram_user_id',
            new_name='telegram_id',
        ),
    ]
