# Generated by Django 5.1.6 on 2025-03-01 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_rename_telegram_user_id_trackeraccount_telegram_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='max_users',
            field=models.PositiveSmallIntegerField(default=5),
        ),
    ]
