# Generated by Django 5.1.6 on 2025-03-01 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_alter_telegramuser_max_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackeduser',
            name='tracker_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tracked_users', to='tracker.trackeraccount'),
        ),
    ]
